baseURL = 'https://snailtrail.org/'
languageCode = 'en-gb'
title = 'SnailTrail'
theme = 'hugo-theme-cleanwhite'
enableEmoji = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/roma-hdr.jpg"
  SEOTitle = "Snailtrail"
  description = "Random wanderings of BrianTheSnail"
  keyword = "Romahome, Campervan"
  slogan = "Keep On Slitherin'"
  upstreamAttribution = true

  image_404 = "images/404-bg.jpg"
  title_404 = "Sorry - this page doesn't exist'"
  omit_categories = false


# Sidebar settings
  sidebar_about_description = "Mollusc extraordinaire"
  sidebar_avatar = "/images/brian.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false
  featured_condition_size = 1 

  showtoc = false 
